---
- hosts: YOUR_HOSTS
  become: yes
  gather_facts: no
  vars_files:
    - "vars/install.yml"
  roles:
    - timezone
    - nginx_install
    - mariadb_install
    - php_install
    - wordpress_install
