---
- name: Install Nginx
  apt: 
    name: nginx
    state: latest
    update_cache: yes

- name: Set nginx.conf
  copy:
    src: nginx.conf
    dest: "{{nginx_place}}/nginx.conf"

- name: Start Nginx
  systemd:
    name: nginx.service
    state: restarted
    daemon_reload: yes
    enabled: yes
