---
- name: Install Nginx
  apt: 
    name: nginx
    state: latest
    update_cache: yes

- name: Set nginx.conf
  file:
    src: nginx.conf
    dest: "{{nginx_place}}/nginx.conf"
    owner: root
    group: root
    mode: 0644

- name: Start Nginx
  systemd:
    name: nginx.service
    state: restarted
    daemon_reload: yes
    enabled: yes