---
- name: install mariadb
  apt: 
    name: mariadb-server
    state: latest
    update_cache: yes

- name: start mariadb
  systemd:
    name: mariadb.service
    state: restarted
    daemon_reload: yes
    enabled: yes