---
- name: Unarchive tar.gz
  ansible.builtin.unarchive:
    src: "{{ dokuwiki_url }}"
    dest: /tmp
    remote_src: yes

- name: Copy dokuwiki into /var/www
  copy:
    src: "/tmp/dokuwiki-{{ dokuwiki_version }}/"
    dest: /var/www/dokuwiki
    remote_src: yes
    directory_mode: 0644
    group: www-data
    owner: www-data

- name: Replace document root
  copy:
    src: 000-default.conf
    dest: "{{default_place}}/000-default.conf"
    owner: root
    group: root
    mode: 0644

- name: restart apache
  systemd:
    name: apache2.service
    state: restarted
    daemon_reload: yes
    enabled: yes
