---
- name: download dokuwiki the latest stable release
  shell: wget {{dokuwiki_url}}
  args:
    chdir: /var/www

- name: uncompress dokuwiki
  shell: tar xvf dokuwiki-stable.tgz
  args:
    chdir: /var/www

- name: rename dir
  shell: mv dokuwiki-*/ dokuwiki
  args:
    chdir: /var/www

- name: Change directory permission
  shell: chown -R www-data:www-data /var/www/dokuwiki/
  args:
    chdir: /var/www

- name: Replace document root 
  copy:
    src: 000-default.conf
    dest: "{{default_place}}/000-default.conf"
    owner: root
    group: root
    mode: 0644

- name: restart apache
  systemd: 
    name: apache2.service
    state: restarted
    daemon_reload: yes
    enabled: yes